# Generated by Django 4.0.3 on 2022-04-26 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='galleryimage',
            old_name='customer',
            new_name='Customer_name',
        ),
        migrations.RenameField(
            model_name='galleryimage',
            old_name='image',
            new_name='Image',
        ),
    ]
